global:
  resolve_timeout: 5m

routea:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "email"

receivers:
- name: "email"
  email_configs:
  - to: "dotruong576@gmail.com"
    from: "dotruong576@gmail.com"
    smarthost: "smtp.gmail.com:587"
    auth_username: dotruong576@gmail.com
    auth_password: ${EMAIL_PASSWORD}
    require_tls: true
    tls_config:
      insecure_skip_verify: false
