---
# Deploy configuration to Cisco device ISP
- name: Deploy configuration to Cisco device ISP
  hosts: cisco_devices_ISP
  gather_facts: false
  tasks:
    - name: Configure DHCP server
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "ip dhcp pool vlan1"
          - "network 192.168.1.0 255.255.255.0"
          - "default-router 192.168.1.1"
          - "ip dhcp pool vlan2"
          - "network 192.168.2.0 255.255.255.0"
          - "default-router 192.168.2.1"
          - "ip dhcp pool vlan3"
          - "network 192.168.3.0 255.255.255.0"
          - "default-router 192.168.3.1"

- name: Deploy configuration to Cisco device ISP 1
  hosts: cisco_devices_ISP_1
  gather_facts: false
  tasks:
    - name: Configure Ethernet0/2
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface e0/2"
          - "no shutdown"
          - "ip address 172.16.11.1 255.255.255.0"
    - name: Configure Static Route
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "ip route 192.168.1.0 255.255.255.0 172.16.11.2"
          - "ip route 192.168.2.0 255.255.255.0 172.16.11.2"
          - "ip route 192.168.3.0 255.255.255.0 172.16.11.2"
          
- name: Deploy configuration to Cisco device ISP 2
  hosts: cisco_devices_ISP_2
  gather_facts: false
  tasks:
    - name: Configure Ethernet0/2
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface e0/2"
          - "no shutdown"
          - "ip address 172.16.12.1 255.255.255.0"
    - name: Configure Static Route
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "ip route 192.168.1.0 255.255.255.0 172.16.12.2"
          - "ip route 192.168.2.0 255.255.255.0 172.16.12.2"
          - "ip route 192.168.3.0 255.255.255.0 172.16.12.2"
          
# Deploy configuration to Cisco device CORE
- name: Deploy configuration to Cisco device CORE
  hosts: cisco_devices_CORE
  gather_facts: false
  tasks:
    - name: Configure Ethernet0/1-2
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface range Ethernet0/1-2"
          - "no sh"
    - name: Configure Ethernet0/2.1
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet0/2.1"
          - "encapsulation dot1Q 1"
          - "ip address 192.168.1.1 255.255.255.0"
    - name: Configure Ethernet0/2.2
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet0/2.2"
          - "encapsulation dot1Q 2"
          - "ip address 192.168.2.1 255.255.255.0"
    - name: Configure Ethernet0/2.3
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet0/2.3"
          - "encapsulation dot1Q 3"
          - "ip address 192.168.3.1 255.255.255.0"
    
- name: Deploy configuration to Cisco device CORE 1
  hosts: cisco_devices_CORE_1
  gather_facts: false
  tasks:
    - name: Configure Ethernet0/1
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet0/1"
          - "ip address 172.16.11.2 255.255.255.0"
    - name: Configure Ethernet0/2.1
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet0/2.1"
          - "ip helper-address 172.16.11.1"
    - name: Configure Ethernet0/2.2
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet0/2.2"
          - "ip helper-address 172.16.11.1"
    - name: Configure Ethernet0/2.3
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet0/2.3"
          - "ip helper-address 172.16.11.1"
    
- name: Deploy configuration to Cisco device CORE 2
  hosts: cisco_devices_CORE_2
  gather_facts: false
  tasks:
    - name: Configure Ethernet0/1
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet0/1"
          - "ip address 172.16.12.2 255.255.255.0"
    - name: Configure Ethernet0/2.1
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet0/2.1"
          - "ip helper-address 172.16.12.1"
    - name: Configure Ethernet0/2.2
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet0/2.2"
          - "ip helper-address 172.16.12.1"
    - name: Configure Ethernet0/2.3
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet0/2.3"
          - "ip helper-address 172.16.12.1"
    
# Deploy configuration to Cisco device DIST
- name: Deploy configuration to Cisco device DIST
  hosts: cisco_devices_DIST
  gather_facts: false
  tasks:
    - name: Configure Ethernet0/1
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet0/1"
          - "switchport"
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"
    - name: Configure Ethernet1/0-2
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface range Ethernet1/0-2"
          - "switchport"
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"
    - name: Configure LACP Ethernet0/2-3
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface range Ethernet0/2-3"
          - "channel-group 1 mode active"
          - "switchport"
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"

- name: Deploy configuration to Cisco device DIST 1
  hosts: cisco_devices_DIST_1
  gather_facts: false
  tasks:
    - name: Configure IP vlan dist 1
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface vlan 1"
          - "ip address 192.168.1.251 255.255.255.0"
          - "no sh"
          - "interface vlan 2"
          - "ip address 192.168.2.251 255.255.255.0"
          - "no sh"
          - "interface vlan 3"
          - "ip address 192.168.3.251 255.255.255.0"
          - "no sh"
    - name: Configure STP
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "spanning-tree vlan 1 priority 0"
          - "spanning-tree vlan 2 priority 0"
          - "spanning-tree vlan 3 priority 0"

- name: Deploy configuration to Cisco device DIST 2
  hosts: cisco_devices_DIST_2
  gather_facts: false
  tasks:
    - name: Configure IP vlan dist 2
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface vlan 1"
          - "ip address 192.168.1.252 255.255.255.0"
          - "no sh"
          - "interface vlan 2"
          - "ip address 192.168.2.252 255.255.255.0"
          - "no sh"
          - "interface vlan 3"
          - "ip address 192.168.3.252 255.255.255.0"
          - "no sh"
          
    - name: Configure STP
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "spanning-tree vlan 1 priority 4096"
          - "spanning-tree vlan 2 priority 4096"
          - "spanning-tree vlan 3 priority 4096"
      
# Deploy configuration to Cisco device ACCESS
- name: Deploy configuration to Cisco device ACCESS
  hosts: cisco_devices_ACC
  gather_facts: false
  tasks:
    - name: Configure Ethernet0/1
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet0/1"
          - "switchport"
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"
          - "spanning-tree cost 10"
    - name: Configure Ethernet0/2
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet0/2"
          - "switchport"
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"
          - "spanning-tree cost 100"

- name: Deploy configuration to Cisco device ACCESS 1
  hosts: cisco_devices_ACC_1
  gather_facts: false
  tasks:
    - name: Configure Ethernet1/0
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet1/0"
          - "switchport"
          - "switchport mode access"
          - "switchport access vlan 1"
    - name: Configure Ethernet1/1
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet1/1"
          - "switchport"
          - "switchport mode access"
          - "switchport access vlan 2"
    - name: Configure IP vlan acc 1
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface vlan 1"
          - "ip address 192.168.1.250 255.255.255.0"
          - "no sh"
          - "interface vlan 2"
          - "ip address 192.168.2.250 255.255.255.0"
          - "no sh"
          - "interface vlan 3"
          - "ip address 192.168.3.250 255.255.255.0"
          - "no sh"
- name: Deploy configuration to Cisco device ACCESS 2
  hosts: cisco_devices_ACC_2
  gather_facts: false
  tasks:
    - name: Configure Ethernet1/1
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet1/0"
          - "switchport"
          - "switchport mode access"
          - "switchport access vlan 3"
    - name: Configure Ethernet1/0
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet1/1"
          - "switchport"
          - "switchport mode access"
          - "switchport access vlan 1"
    - name: Configure IP vlan acc 2
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface vlan 1"
          - "ip address 192.168.1.253 255.255.255.0"
          - "no sh"
          - "interface vlan 2"
          - "ip address 192.168.2.253 255.255.255.0"
          - "no sh"
          - "interface vlan 3"
          - "ip address 192.168.3.253 255.255.255.0"
          - "no sh"
- name: Deploy configuration to Cisco device ACCESS 3
  hosts: cisco_devices_ACC_3
  gather_facts: false
  tasks:
    - name: Configure Ethernet1/0
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet1/0"
          - "switchport"
          - "switchport mode access"
          - "switchport access vlan 2"
    - name: Configure Ethernet1/1
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet1/1"
          - "switchport"
          - "switchport mode access"
          - "switchport access vlan 3"
    - name: Configure IP vlan acc 3
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface vlan 1"
          - "ip address 192.168.1.254 255.255.255.0"
          - "no sh"
          - "interface vlan 2"
          - "ip address 192.168.2.254 255.255.255.0"
          - "no sh"
          - "interface vlan 3"
          - "ip address 192.168.3.254 255.255.255.0"
          - "no sh"
