{
 "title": "Switch-Cisco",
 "tags": [
  "cisco",
  "switch"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "query_result(sum by (job) (ifInOctets{job=\"snmp-exporter-cisco-switch\"}))"
    }
   },
   {
    "name": "Device",
    "query": {
     "query": "query_result(sum by (instance)(ifInOctets{job=\"$Job\"}))"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Switch Cisco Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"snmp-exporter-cisco-switch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status - Switch Cisco",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"snmp-exporter-cisco-switch\"}==1)",
     "legendFormat": "UP"
    },
    {
     "expr": "count(up{job=\"snmp-exporter-cisco-switch\"}) - count(up{job=\"snmp-exporter-cisco-switch\"} == 1)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Allocated Throughput",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(ifInOctets{job=\"snmp-exporter-cisco-switch\",instance=\"$Device\"}[1m])) + sum(irate(ifOutOctets{job=\"snmp-exporter-cisco-switch\",instance=\"$Device\"}[1m])))*8"
    }
   ]
  },
  {
   "title": "Total Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(ifOutOctets{job=\"snmp-exporter-cisco-switch\", instance=\"$Device\"}[1m]))*8",
     "legendFormat": "Outbound"
    },
    {
     "expr": "sum(irate(ifInOctets{job=\"snmp-exporter-cisco-switch\", instance=\"$Device\"}[1m]))*8",
     "legendFormat": "Inbound"
    }
   ]
  },
  { "title": "Octet interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Port-Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "ifOperStatus{job=\"snmp-exporter-cisco-switch\", instance=\"$Device\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(ifInOctets{job=\"snmp-exporter-cisco-switch\", instance=\"$Device\"}[1m])*8",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(ifOutOctets{job=\"snmp-exporter-cisco-switch\", instance=\"$Device\"}[1m])*8",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}