# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  scrape_timeout: 10s
#
#enable_admin_api: true
# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:  ["alert-manager:9093"]


# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - ./rules/network-rules.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["192.168.101.146:9090"]
        labels:
          hostname: PrometheusProd
          type: docker


  - job_name: "node-exporter"
    static_configs:
      - targets: ["192.168.101.146:9100"]
        labels:
          hostname: linux
          type: linux-server

###### SNMP ######
#switch cisco
  - job_name: "snmp-exporter-cisco-switch"
    static_configs:
      - targets: ['192.168.101.11']
        labels:
          hostname: "ISP-Router-1"
          type: cisco
      - targets: ['192.168.101.12']
        labels:
          hostname: "ISP-Router-2"
          type: cisco
      - targets: ['192.168.101.13']
        labels:
          hostname: "Core-Router-1"
          type: cisco
      - targets: ['192.168.101.14']
        labels:
          hostname: "Core-Router-2"
          type: cisco
      - targets: ['192.168.101.15']
        labels:
          hostname: "DIST-1"
          type: cisco
      - targets: ['192.168.101.16']
        labels:
          hostname: "DIST-2"
          type: cisco
      - targets: ['192.168.101.21']
        labels:
          hostname: "ACC-1"
          type: cisco
      - targets: ['192.168.101.22']
        labels:
          hostname: "ACC-2"
          type: cisco
      - targets: ['192.168.101.23']
        labels:
          hostname: "ACC-3"
          type: cisco

    metrics_path: /snmp
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: '192.168.101.146:9116'
    tls_config:
      insecure_skip_verify: true
