---
# Deploy configuration to Cisco device ACCESS
- name: Deploy configuration to Cisco device ACCESS
  hosts: cisco_devices_ACC
  gather_facts: false
  tasks:
    - name: Configure Ethernet0/1
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet0/1"
          - "switchport"
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"
          - "spanning-tree cost 10"
    - name: Configure Ethernet0/2
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet0/2"
          - "switchport"
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"
          - "spanning-tree cost 100"

- name: Deploy configuration to Cisco device ACCESS 1
  hosts: cisco_devices_ACC_1
  gather_facts: false
  tasks:
    - name: Configure Ethernet1/0
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet1/0"
          - "switchport"
          - "switchport mode access"
          - "switchport access vlan 1"
    - name: Configure Ethernet1/1
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet1/1"
          - "switchport"
          - "switchport mode access"
          - "switchport access vlan 2"
    - name: Configure IP vlan acc 1
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface vlan 1"
          - "ip address 192.168.1.250 255.255.255.0"
          - "no sh"
          - "interface vlan 2"
          - "ip address 192.168.2.250 255.255.255.0"
          - "no sh"
          - "interface vlan 3"
          - "ip address 192.168.3.250 255.255.255.0"
          - "no sh"
- name: Deploy configuration to Cisco device ACCESS 2
  hosts: cisco_devices_ACC_2
  gather_facts: false
  tasks:
    - name: Configure Ethernet1/1
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet1/0"
          - "switchport"
          - "switchport mode access"
          - "switchport access vlan 3"
    - name: Configure Ethernet1/0
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet1/1"
          - "switchport"
          - "switchport mode access"
          - "switchport access vlan 1"
    - name: Configure IP vlan acc 2
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface vlan 1"
          - "ip address 192.168.1.253 255.255.255.0"
          - "no sh"
          - "interface vlan 2"
          - "ip address 192.168.2.253 255.255.255.0"
          - "no sh"
          - "interface vlan 3"
          - "ip address 192.168.3.253 255.255.255.0"
          - "no sh"
- name: Deploy configuration to Cisco device ACCESS 3
  hosts: cisco_devices_ACC_3
  gather_facts: false
  tasks:
    - name: Configure Ethernet1/0
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet1/0"
          - "switchport"
          - "switchport mode access"
          - "switchport access vlan 2"
    - name: Configure Ethernet1/1
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface Ethernet1/1"
          - "switchport"
          - "switchport mode access"
          - "switchport access vlan 3"
    - name: Configure IP vlan acc 3
      cisco.ios.ios_command:
        commands:
          - "enable"
          - "config terminal"
          - "interface vlan 1"
          - "ip address 192.168.1.254 255.255.255.0"
          - "no sh"
          - "interface vlan 2"
          - "ip address 192.168.2.254 255.255.255.0"
          - "no sh"
          - "interface vlan 3"
          - "ip address 192.168.3.254 255.255.255.0"
          - "no sh"
